### ISSUE TITLE
Some menu items remain highlighted

### ISSUE THREAD

**Issue by GuidoBartoli** [singalen/wesnoth#39] opened 2017-08-17 21:34 UTC
​In the Preferences panel, as well as in other windows with scrolling lists, some items remain highlighted while changing from one to another. In the attached screenshot, only "Multiplayer" should be highlighted,
 not Display and Sound that were previously selected.
![img_0542](https://user-images.githubusercontent.com/16103676/29434737-956306b8-83a4-11e7-8a85-dab18f287b8d.jpg)

**Comment by singalen** [comment] 2017-08-19 05:54
Thanks. Duplicate of #2 though.

**Closed as completed** 2017-08-19 05:54 UTC
